#! /usr/bin/env python
import sys
import os

# Have to add service code to python's search path before imports
BASE_PATH = os.path.dirname(os.path.dirname(__file__))
sys.path.append(BASE_PATH)

from waldo_cdc.workers import HTTPWorker, NotificationWorker
from waldo_common.process_management import SubprocessManager


manager = SubprocessManager(worker_classes=[NotificationWorker], health_check_worker_class=HTTPWorker)
manager.start()
